### ISSUE TITLE
typescript declaration error, vue has no default export

### ISSUE THREAD

**Issue by agentschmitt** [kaorun343/vue-property-decorator#13]
After updating from version 3.4 to 4.0 i am getting type script errors.

ERROR in node_modules\vue-class-component\lib\declarations.d.ts
(1,8): error TS1192: Module '"node_modules/vue/types/index"' has no default export.
ERROR in node_modules\vue-class-component\lib\index.d.ts
(1,8): error TS1192: Module 'node_modules/vue/types/index"' has no default export.
ERROR in node_modules\vue-property-decorator\lib\vue-property-decorator.d.ts
(1,8): error TS1192: Module '"node_modules/vue/types/index"' has no default export.

It seems you changed import of vue in 4.0 which is causing the issue:
from: import * as Vue from 'vue';
to: import Vue from 'vue';

my package versions:
"vue": "~2.2.1",
"typescript": "~2.2.1"

my tsconfig:
  "compilerOptions": {
    "module": "amd",
    "target": "es5",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitOnError": false,
    "lib": [
      "es2016",
      "dom"
    ],
    "moduleResolution": "node",
    "skipLibCheck": true
  }

**Comment by kaorun343** [comment]
https://vuejs.org/v2/guide/typescript.html

Please set `allowSyntheticDefaultImports` to true.

**Comment by agentschmitt** [comment]
thx this solves the problem and since this is the recommend configuration from vue i will change my project to that.
